version: 2
updates:
  - package-ecosystem: npm
    directory: /functions
    schedule:
      interval: monthly
    groups:
      firebase:
        patterns:
          - firebase-*
      development:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
